sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - make travisci-install
script:
  - make travisci-test
  - coverage run --source python_filmaffinity setup.py test
after_success:
  - coveralls
